# Generated by Django 4.2.3 on 2023-09-09 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_studentmodel_alter_moviemodel_description"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="moviemodel",
            options={"verbose_name_plural": "MovieModel"},
        ),
        migrations.AlterModelOptions(
            name="studentmodel",
            options={"verbose_name_plural": "StudentModel"},
        ),
    ]
